"use client";

import { useEffect, useState } from "react";
import { PrimaryBlock, SectionHeader, StatCard } from "./ui-primitives";

type Integrity={generatedAt:string;counts:{companies:number;documents:number;activeDocuments:number;archivedDocuments:number;relationEdges:number;orphanDocuments:number;multiCompanyDocuments:number;missingCurrent:number};orphanDocuments:{id:string;title:string;companyName:string;sourceKey:string;notionUrl:string}[];multiCompanyDocuments:{id:string;title:string;companyName:string;notionUrl:string}[];missingCurrent:{id:string;name:string;notionUrl:string}[]};

export function NotionIntegrity(){
  const [data,setData]=useState<Integrity|null>(null);const [error,setError]=useState("");
  useEffect(()=>{fetch("/api/notion/integrity",{cache:"no-store"}).then(async response=>{const payload: Integrity & { error?: string }=await response.json();if(!response.ok)throw new Error(payload.error??"Audit indisponible");setData(payload)}).catch(reason=>setError(reason instanceof Error?reason.message:"Audit indisponible"))},[]);
  if(error)return <p className="notion-sync-message" role="status">{error}</p>;
  if(!data)return <PrimaryBlock as="section" className="live-portfolio-state"><strong>Audit des relations en cours…</strong><span>Lecture des documents et des pointeurs Current.</span></PrimaryBlock>;
  const cards=[ ["Entreprises",data.counts.companies,"Base Companies"],["Documents actifs",data.counts.activeDocuments,"hors Archives"],["Relations indexées",data.counts.relationEdges,"toutes propriétés"],["Documents orphelins",data.counts.orphanDocuments,"à rattacher"],["Relations multiples",data.counts.multiCompanyDocuments,"plusieurs entreprises"],["Current manquants",data.counts.missingCurrent,"fiches incomplètes"] ];
  return <><SectionHeader eyebrow="Pilotage documentaire" title="Intégrité Notion" description="Contrôle en lecture seule de la qualité des relations importées. Aucun document n’est modifié." meta={<span className="analysis-total">Mis à jour {new Date(data.generatedAt).toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}</span>} /><section className="integrity-grid">{cards.map(([label,value,detail])=><StatCard label={label} value={value} detail={detail} className={Number(value)>0&&/orphelins|multiples|manquants/.test(String(label))?"integrity-warning":""} key={String(label)} />)}</section><section className="company-main-grid integrity-sections"><PrimaryBlock as="article" className="detail-card"><p className="eyebrow">À rattacher</p><h2>Documents sans entreprise</h2>{data.orphanDocuments.length?data.orphanDocuments.map(document=><a className="integrity-row" href={document.notionUrl} target="_blank" rel="noreferrer" key={document.id}><span><strong>{document.title}</strong><small>{document.sourceKey}</small></span><b>Notion ↗</b></a>):<p className="generic-empty">Aucun document orphelin détecté.</p>}</PrimaryBlock><PrimaryBlock as="article" className="detail-card"><p className="eyebrow">À vérifier</p><h2>Relations multiples</h2>{data.multiCompanyDocuments.length?data.multiCompanyDocuments.map(document=><a className="integrity-row" href={document.notionUrl} target="_blank" rel="noreferrer" key={document.id}><span><strong>{document.title}</strong><small>{document.companyName}</small></span><b>Notion ↗</b></a>):<p className="generic-empty">Aucun cas multiple détecté.</p>}</PrimaryBlock></section><PrimaryBlock as="section" className="detail-card"><p className="eyebrow">Références Current</p><h2>Entreprises à compléter</h2>{data.missingCurrent.length?<div className="integrity-inline-list">{data.missingCurrent.map(company=><a href={company.notionUrl} target="_blank" rel="noreferrer" key={company.id}>{company.name} ↗</a>)}</div>:<p className="generic-empty">Toutes les entreprises disposent des références attendues.</p>}</PrimaryBlock></>;
}
