import test from 'node:test';
import assert from 'node:assert/strict';
import { withFixture, input, compact, companyId, proposedId } from './fixtures/notion-write-harness.mjs';
test('nominal save re-reads Notion and verifies the server-assigned identity through Core',()=>withFixture({},async f=>{const r=await f.adapter.saveAnalysis(input());assert.equal(r.status,'ok');assert.equal(r.data.status,'verified');assert.notEqual(r.data.analysisId,compact(proposedId));assert.equal(f.creates,1);assert.equal(f.promotions,1);const current=await f.adapter.getCurrentAnalysis(compact(companyId),'business');assert.equal(current.status,'ok');assert.equal(current.data.header.id,r.data.analysisId);assert.ok(f.calls.filter(c=>c.method==='GET'&&c.path.startsWith('/pages/')).length>=6);}));
test('same run re-reads actual state without duplicate or repeat promotion',()=>withFixture({},async f=>{const first=await f.writer(input());const again=await f.writer(input());assert.equal(again.status,'verified');assert.equal(again.analysisId,first.analysisId);assert.equal(f.creates,1);assert.equal(f.promotions,1);}));
test('incompatible same run conflicts before another create',()=>withFixture({},async f=>{await f.writer(input());const changed=input();changed.analysis.header.title='Different';await assert.rejects(f.writer(changed),{code:'stale_request'});assert.equal(f.creates,1);}));
test('stale expectedRevision cannot mutate an existing analysis',()=>withFixture({},async f=>{const r=await f.writer(input());const changed=input({runId:'next-run',expectedRevision:'stale'});changed.analysis.header.id=r.analysisId;await assert.rejects(f.writer(changed),{code:'stale_request'});assert.equal(f.creates,1);}));
test('Company absent fails before persistence',()=>withFixture({missingCompany:true},async f=>{await assert.rejects(f.writer(input()),{code:'not_found'});assert.equal(f.creates,0);}));
test('inconsistent input Company relation is rejected before mutation',()=>withFixture({},async f=>{const changed=input({companyIds:[compact(proposedId)]});const r=await f.adapter.saveAnalysis(changed);assert.equal(r.status,'error');assert.equal(r.error.code,'invalid_input');const malformed=input({companyIds:[5]});assert.equal((await f.adapter.saveAnalysis(malformed)).error.code,'invalid_input');assert.equal(f.creates,0);}));
test('persistence OK / promotion KO returns resumable pending and safely resumes',()=>withFixture({promotionFail:true},async f=>{const r=await f.writer(input());assert.equal(r.status,'promotion_pending');assert.equal(r.persisted,true);assert.equal(r.verified,false);f.flags.promotionFail=false;assert.equal((await f.writer(input())).status,'verified');assert.equal(f.creates,1);}));
test('promotion OK / final verification KO never returns verified',()=>withFixture({failFinalRead:true},async f=>{const r=await f.writer(input());assert.equal(r.status,'partial');assert.equal(r.persisted,true);assert.equal(r.promoted,true);assert.equal(r.verified,false);}));
test('ambiguous create timeout reconciles Run ID before any mutation retry',()=>withFixture({createTimeout:true},async f=>{const r=await f.writer(input());assert.equal(r.status,'verified');assert.equal(f.creates,1);const creation=f.calls.findIndex(c=>c.path==='/pages');assert.ok(f.calls.slice(creation+1).some(c=>c.path.endsWith('/query')));}));
test('ambiguous promotion reconciles Company rather than blindly repeating PATCH',()=>withFixture({promotionTimeout:true},async f=>{assert.equal((await f.writer(input())).status,'verified');assert.equal(f.promotions,1);}));
test('rate limit mutation retries are bounded and do not certify persistence',()=>withFixture({rateLimit:true},async f=>{await assert.rejects(f.writer(input()),{code:'rate_limit'});assert.equal(f.calls.filter(c=>c.path==='/pages').length,3);assert.equal(f.creates,0);}));
test('wrong final Current returns partial, never verified',()=>withFixture({wrongFinalCurrent:true},async f=>{const r=await f.writer(input());assert.equal(r.status,'partial');assert.equal(r.verified,false);}));
test('concurrent same-run writers share the D1 lease and create at most one page',()=>withFixture({},async f=>{const results=await Promise.allSettled([f.writer(input()),f.writer(input())]);assert.equal(f.creates,1);assert.ok(results.some(r=>r.status==='fulfilled'));for(const result of results)if(result.status==='rejected')assert.equal(result.reason.code,'stale_request');else assert.equal(result.value.status,'verified');}));
test('metadata update checks source revision and preserves the existing report body',()=>withFixture({},async f=>{const r=await f.writer(input());const p=f.pages.get(r.analysisId);const changed=input({runId:'update-run',expectedRevision:p.last_edited_time});changed.analysis.header.id=r.analysisId;changed.analysis.header.title='Updated fixture';const saved=await f.writer(changed);assert.equal(saved.status,'verified');assert.equal(saved.analysisId,r.analysisId);assert.equal(f.creates,1);}));
test('position reads source lifecycle: open, closed, absent, inconsistent and invalid',()=>withFixture({},async f=>{
 const save=(id,status,quantity)=>f.sql.prepare('INSERT INTO notion_documents VALUES(?,?,?,?,?,?,?,?,?)').run(id,'portfolio','Fixture position',`https://notion.so/${id}`,'2026-10-02T00:00:00Z',JSON.stringify({Position:{type:'title',title:[{plain_text:'Fixture position'}]},Status:{type:'select',select:{name:status}},Quantity:{type:'number',number:quantity},PRU:{type:'number',number:10},'Current Price':{type:'number',number:12},'Price Currency':{type:'select',select:{name:'EUR'}}}),'[]','','2026-10-02T00:00:00Z');
 const open='44444444-4444-4444-8444-444444444444',closed='55555555-5555-4555-8555-555555555555',bad='66666666-6666-4666-8666-666666666666';
 save(open,'Active',2);save(closed,'Sold',0);save(bad,'Active',0);
 assert.equal((await f.adapter.getPosition(compact(open),{cacheOnly:true})).data.lifecycle,'open');
 assert.equal((await f.adapter.getPosition(compact(closed))).data.lifecycle,'closed');
 assert.equal((await f.adapter.getPosition(compact(proposedId))).data,null);
 assert.equal((await f.adapter.getPosition(compact(bad))).error.code,'mapping');
 assert.equal((await f.adapter.getPosition(' ')).error.code,'invalid_input');
 f.sql.prepare("UPDATE notion_documents SET properties_json=? WHERE page_id=?").run(JSON.stringify({Status:{type:'select',select:{name:'Inactive'}},Quantity:{type:'number',number:0}}),bad);
 assert.equal((await f.adapter.getPosition(compact(bad))).error.code,'mapping','inactive is not proof of closure');
}));

test('unresolved ambiguous create is fenced across replays, not blindly retried',()=>withFixture({createTimeoutBefore:true},async f=>{const r=await f.writer(input());assert.equal(r.status,'partial');assert.equal(r.persisted,false);assert.equal((await f.writer(input())).status,'partial');assert.equal(f.calls.filter(c=>c.path==='/pages').length,1);assert.equal(f.creates,0);}));
test('Draft persistence is readable through MCP Core without promoting Current',()=>withFixture({},async f=>{const draft=input();draft.analysis.header.status='Draft';const r=await f.writer(draft);assert.equal(r.status,'persisted');assert.equal(r.persisted,true);assert.equal(r.promoted,false);assert.equal(r.verified,false);assert.equal(f.promotions,0);const read=await f.api.createInvestmentService(f.db).getAnalysisById(r.analysisId);assert.equal(read.status,'ok');assert.equal(read.data.header.id,r.analysisId);assert.equal(read.data.header.status,'Draft');}));
test('Draft save and replay update only their page indexes and avoid a second create',()=>withFixture({},async f=>{const draft=input();draft.analysis.header.status='Draft';const childrenReads=()=>f.calls.filter(c=>c.method==='GET'&&c.path.startsWith('/blocks/')&&c.path.includes('/children')).length;const first=await f.writer(draft);assert.equal(first.status,'persisted');assert.equal(childrenReads(),1);const link=await f.db.prepare('SELECT company_page_id FROM notion_document_companies WHERE document_page_id=?').bind(f.pages.get(first.analysisId).id).first();assert.equal(compact(link.company_page_id),compact(companyId));const relation=await f.db.prepare("SELECT target_page_id FROM notion_relations WHERE source_page_id=? AND property_name='Company'").bind(f.pages.get(first.analysisId).id).first();assert.equal(compact(relation.target_page_id),compact(companyId));await f.db.prepare("INSERT INTO notion_document_companies VALUES ('unrelated','unrelated','notion-relation','now')").run();const replay=await f.writer(draft);assert.equal(replay.status,'persisted');assert.equal(replay.analysisId,first.analysisId);assert.equal(childrenReads(),3);assert.equal((await f.db.prepare("SELECT count(*) AS n FROM notion_document_companies WHERE document_page_id='unrelated'").first()).n,1);assert.equal(f.creates,1);assert.equal(f.promotions,0);}));
test('adapter canonicalizes dashed update identity before receipt validation',()=>withFixture({},async f=>{const r=await f.writer(input());const existing=f.pages.get(r.analysisId),changed=input({runId:'dashed-update',expectedRevision:existing.last_edited_time});changed.analysis.header.id=existing.id;changed.companyIds=[companyId];changed.analysis.header.companyIds=[companyId];changed.analysis.header.title='Updated dashed';assert.equal((await f.adapter.saveAnalysis(changed)).data.status,'verified');}));

test('long report is written in bounded chunks and completely re-read before verified',()=>withFixture({},async f=>{const report=input();report.analysis.content.blocks=Array.from({length:205},(_,n)=>({id:`p-${n}`,sourceIds:[`source-${n}`],type:'paragraph',text:[{text:`Paragraph ${n}`,marks:[],href:null}]}));const r=await f.writer(report);assert.equal(r.status,'verified');assert.equal(f.blocks.get(r.analysisId).length,205);assert.equal(f.calls.filter(c=>c.method==='PATCH'&&c.path.endsWith('/children')).length,2);}));
test('ambiguous append reconciles the exact block prefix without duplicating content',()=>withFixture({appendTimeout:true},async f=>{const report=input();report.analysis.content.blocks=Array.from({length:105},(_,n)=>({id:`p-${n}`,sourceIds:[`source-${n}`],type:'paragraph',text:[{text:`Paragraph ${n}`,marks:[],href:null}]}));const r=await f.writer(report);assert.equal(r.status,'verified');assert.equal(f.blocks.get(r.analysisId).length,105);assert.equal(f.calls.filter(c=>c.method==='PATCH'&&c.path.endsWith('/children')).length,1);}));

test('lost D1 lease is detected before a Current mutation',()=>withFixture({stealLease:true},async f=>{const r=await f.writer(input());assert.equal(r.status,'partial');assert.equal(r.verified,false);assert.equal(f.promotions,0);}));

test('production shared Run ID remains idempotent independently for Business and Valuation modules',()=>withFixture({},async f=>{const business=await f.writer(input());const valuation=input();valuation.analysis.kind='valuation';valuation.analysis.header.family='valuation';valuation.analysis.header.agent='Valuation Analyst';valuation.analysis.header.title='Fixture valuation';const result=await f.writer(valuation);assert.equal(result.status,'verified');assert.notEqual(result.analysisId,business.analysisId);assert.equal((await f.writer(input())).analysisId,business.analysisId);assert.equal((await f.writer(valuation)).analysisId,result.analysisId);assert.equal(f.creates,2);}));

test('physical Company must be a relation; schema mismatch cannot yield verified',()=>withFixture({badCompanyType:true},async f=>{await assert.rejects(f.writer(input()),{code:'mapping'});assert.equal(f.creates,0);}));

test('Company archived during final verification cannot yield verified',()=>withFixture({archiveFinalCompany:true},async f=>{const r=await f.writer(input());assert.equal(r.status,'partial');assert.equal(r.verified,false);}));

test('revisioned update cannot retype a Business Current page as Valuation',()=>withFixture({},async f=>{const saved=await f.writer(input()),existing=f.pages.get(saved.analysisId);const changed=input({runId:'different-module-update',expectedRevision:existing.last_edited_time});changed.analysis.kind='valuation';changed.analysis.header.family='valuation';changed.analysis.header.agent='Valuation Analyst';changed.analysis.header.id=saved.analysisId;await assert.rejects(f.writer(changed),{code:'stale_request'});assert.equal(existing.properties.Agent.select.name,'Business Analyst');assert.equal(f.creates,1);assert.equal(f.promotions,1);}));
