import type {
  CompanyDetail as CompanyDetailData,
  CompanyDocument,
  CompanyListItem,
  LivePortfolio,
} from "../app/lib/investment-data";

export const reference = {
  id: "ref-business",
  kind: "business" as const,
  title: "Current Business Analysis",
  agent: "Business Analyst",
  score: "82",
  verdict: "Quality compounder",
  confidence: "High",
  status: "Current",
  date: "2026-09-18",
  lastEditedTime: "2026-09-18T10:00:00.000Z",
  notionUrl: "#",
};

export const company: CompanyListItem = {
  id: "company-example",
  name: "Advanced Micro Devices — Long Reference Name",
  ticker: "AMD",
  sector: "Technology",
  industry: "Semiconductors and accelerated computing",
  ownershipStatus: "Owned",
  watchlistMembership: true,
  monitoringStatus: "Monitoring",
  businessScore: 82,
  businessVerdict: "Quality compounder",
  researchStage: "Current",
  researchPriority: "High",
  lastAnalysis: "2026-09-18",
  themes: ["AI infrastructure", "Quality", "Data center"],
  country: "United States",
  currency: "USD",
  exchange: "NASDAQ",
  dataCompleteness: "Complete",
  notionUrl: "#",
  researchReferences: [reference],
};

export const emptyCompanies = { companies: [] };

export const document: CompanyDocument = {
  previewSummaryItems: ["Strong operating quality", "Valuation requires discipline"],
  id: "doc-business",
  title: "Current Business Analysis",
  sourceKey: "analyses",
  category: "business",
  agent: "Business Analyst",
  notionUrl: "#",
  lastEditedTime: "2026-09-18T10:00:00.000Z",
  plainText: "Reference document",
  summary: "A compact current analysis used only for the reference screen.",
  handoffSummary: "Maintain monitoring.",
  status: "Current",
  score: "82",
  verdict: "Quality compounder",
  confidence: "High",
  date: "2026-09-18",
  relations: [],
  archived: false,
  current: true,
};

export const companyDetail: CompanyDetailData = {
  ...company,
  analyses: [document],
  earnings: [],
  decisions: [],
  portfolioDocuments: [],
  archives: [],
};

const slice = {
  marketValueEur: 10000,
  investedValueEur: 9300,
  cashValueEur: 700,
  costBasisEur: 9000,
  pnlEur: 300,
  pnlPercent: 3.3,
  brokerCostBasisEur: 9000,
  brokerPnlEur: 300,
  brokerPnlPercent: 3.3,
  positions: 2,
};

export const livePortfolio: LivePortfolio = {
  generatedAt: "2026-09-19T09:00:00.000Z",
  quoteAsOf: "2026-09-19T08:55:00.000Z",
  oldestQuoteAsOf: "2026-09-19T08:55:00.000Z",
  targetSource: "Notion Portfolio · Target Weight 10k + Target Weight",
  targetLines: [{ id: "target-example", name: "Example Corp", target10kWeight: 25, target10kEur: 2500, target25kWeight: 25, target25kEur: 6250 }],
  targetTotals: { target10kWeight: 25, target25kWeight: 25 },
  totals: slice,
  slices: { total: slice, CTO: slice, PEA: { ...slice, marketValueEur: 0, positions: 0 } },
  positions: [{
    id: "position-example",
    targetId: "target-example",
    name: "Example Corp — CTO",
    instrumentType: "Equity",
    account: "CTO",
    sector: "Technology",
    industry: "Software",
    themes: ["AI infrastructure"],
    primaryTheme: "AI infrastructure",
    country: "United States",
    countryExposures: [{ name: "United States", weight: 1 }],
    sectorExposures: [{ name: "Technology", weight: 1 }],
    themeExposures: [{ name: "AI infrastructure", weight: 1 }],
    quantity: 10,
    pruEur: 900,
    brokerPruEur: 900,
    pruSource: "notion-pru",
    costBasisEur: 9000,
    brokerCostBasisEur: 9000,
    marketValueEur: 9300,
    pnlEur: 300,
    pnlPercent: 3.3,
    brokerPnlEur: 300,
    brokerPnlPercent: 3.3,
    weight: 93,
    targetWeight: 25,
    targetEur: 2500,
    target10kWeight: 25,
    target10kEur: 2500,
    quoteSymbol: "EXM",
    nativePrice: 1000,
    nativeCurrency: "USD",
    eurPrice: 930,
    fxRate: 0.93,
    fxMarketTime: "2026-09-19T08:55:00.000Z",
    fetchedAt: "2026-09-19T08:55:00.000Z",
    quoteWarnings: [],
    changePercent: 1.2,
    quoteSource: "reference",
    quoteFreshness: "fresh",
    marketTime: "2026-09-19T08:55:00.000Z",
    companyIds: [company.id],
    notionUrl: "#",
    warning: null,
  }],
  sectors: [{ name: "Technology", valueEur: 9300, weight: 93 }, { name: "Cash", valueEur: 700, weight: 7 }],
  coverage: { live: 1, manual: 0, stale: 0, unavailable: 0, cash: 1, total: 2 },
  reconciliation: { status: "ok", coherent: 2, warnings: 0, errors: 0, issues: [], accountChecks: { CTO: { linesValueEur: 9300, sliceValueEur: 10000, deltaEur: 700 } } },
  calculation: { pnlScope: "unrealized-open-positions", realizedPnlAvailable: false, feesIncluded: false, dividendsIncluded: false, source: "Notion PRU + live quotes + FX" },
};

export const targetAllocationStates: LivePortfolio = {
  ...livePortfolio,
  targetLines: [
    { ...livePortfolio.targetLines[0], target25kWeight: 25, target25kEur: 6250 },
    { id: "target-building", name: "Construction", target10kWeight: 75, target10kEur: 7500, target25kWeight: 7, target25kEur: 1750 },
    { id: "target-remaining", name: "À construire", target10kWeight: 0, target10kEur: 0, target25kWeight: 68, target25kEur: 17000 },
  ],
  targetTotals: { target10kWeight: 100, target25kWeight: 100 },
  positions: [
    {
      ...livePortfolio.positions[0],
      marketValueEur: 9100,
      costBasisEur: 8800,
      brokerCostBasisEur: 8800,
      pnlEur: 300,
      pnlPercent: 3.4,
      brokerPnlEur: 300,
      brokerPnlPercent: 3.4,
      weight: 91,
      pruEur: 880,
      brokerPruEur: 880,
      eurPrice: 910,
      fxRate: 0.91,
      targetEur: 2500,
      target10kEur: 2500,
    },
    {
      ...livePortfolio.positions[0],
      id: "position-outside-target",
      targetId: "target-outside",
      name: "Position hors cible — CTO",
      quantity: 1,
      pruEur: 200,
      brokerPruEur: 200,
      costBasisEur: 200,
      brokerCostBasisEur: 200,
      marketValueEur: 200,
      pnlEur: 0,
      pnlPercent: 0,
      brokerPnlEur: 0,
      brokerPnlPercent: 0,
      weight: 2,
      targetWeight: 0,
      targetEur: 0,
      target10kWeight: 0,
      target10kEur: 0,
      quoteSymbol: "OUT",
      nativePrice: 200,
      nativeCurrency: "EUR",
      eurPrice: 200,
      fxRate: 1,
      companyIds: [],
    },
  ],
};
