import type {
  CompanyDetail as CompanyDetailData,
  CompanyDocument,
  CompanyListItem,
  LivePortfolio,
  ResearchDocument,
  WatchlistData,
} from "../app/lib/investment-data";

export const reference = {
  id: "ref-business",
  kind: "business" as const,
  title: "Current Business Analysis",
  agent: "Business Analyst",
  score: "82",
  verdict: "Quality compounder",
  confidence: "High",
  status: "Current",
  date: "2026-09-18",
  lastEditedTime: "2026-09-18T10:00:00.000Z",
  notionUrl: "#",
};

export const company: CompanyListItem = {
  id: "company-example",
  name: "Advanced Micro Devices — Long Reference Name",
  ticker: "AMD",
  sector: "Technology",
  industry: "Semiconductors and accelerated computing",
  status: "Active",
  ownershipStatus: "Owned",
  watchlistMembership: true,
  monitoringStatus: "Monitoring",
  decision: "Hold",
  lifecycleStatus: "Current",
  businessScore: 82,
  businessVerdict: "Quality compounder",
  researchStage: "Current",
  researchPriority: "High",
  lastAnalysis: "2026-09-18",
  themes: ["AI infrastructure", "Quality", "Data center"],
  country: "United States",
  currency: "USD",
  exchange: "NASDAQ",
  dataCompleteness: "Complete",
  owned: true,
  notionUrl: "#",
  researchReferences: [reference],
};

export const lumentumCompany: CompanyListItem = {
  ...company,
  id: "company-lumentum",
  name: "Lumentum Holdings",
  ticker: "LITE",
  industry: "Optical components and cloud networking",
  ownershipStatus: "Owned",
  watchlistMembership: false,
  monitoringStatus: "Owned",
  themes: ["Data center", "Optical networking"],
  researchReferences: [],
};

export const watchlist: WatchlistData = {
  themes: ["AI infrastructure", "Quality", "Data center"],
  items: [
    {
      id: "watch-example",
      name: company.name,
      ticker: company.ticker,
      monitoringStatus: "Monitoring",
      decision: "Hold",
      conviction: "High",
      analysisDate: "2026-09-18",
      themes: company.themes,
      thesis: "Long deterministic thesis label covering AI infrastructure demand, data-center execution, valuation discipline, and the monitoring decision.",
      companyIds: [company.id],
      ownershipStatus: "Owned",
      watchlistMembership: true,
      notionUrl: "#",
    },
  ],
};

export const emptyWatchlist: WatchlistData = { themes: [], items: [] };
export const emptyCompanies = { companies: [] };

export const document: CompanyDocument = {
  previewSummaryItems: ["Strong operating quality", "Valuation requires discipline"],
  id: "doc-business",
  title: "Current Business Analysis",
  sourceKey: "analyses",
  category: "business",
  agent: "Business Analyst",
  notionUrl: "#",
  lastEditedTime: "2026-09-18T10:00:00.000Z",
  plainText: "Reference document",
  summary: "A compact current analysis used only for the reference screen.",
  handoffSummary: "Maintain monitoring.",
  status: "Current",
  score: "82",
  verdict: "Quality compounder",
  confidence: "High",
  date: "2026-09-18",
  relations: [],
  archived: false,
  current: true,
};

export const analysisDocuments: ResearchDocument[] = [
  { ...document, companyName: company.name },
  {
    ...document,
    id: "doc-valuation",
    companyName: company.name,
    title: "Valuation discipline and upside case",
    category: "valuation",
    agent: "Fair Value",
    score: "76",
    verdict: "Attractive with discipline",
  },
];

export const analysesData = { documents: analysisDocuments, counts: { analyses: 4, earnings: 2, portfolio: 1, decisions: 1 } };
export const emptyAnalysesData = { documents: [], counts: {} };

export const companyDetail: CompanyDetailData = {
  ...company,
  analyses: [document],
  earnings: [],
  decisions: [],
  portfolioDocuments: [],
  archives: [],
};

const slice = {
  marketValueEur: 10000,
  investedValueEur: 9300,
  cashValueEur: 700,
  costBasisEur: 9000,
  pnlEur: 300,
  pnlPercent: 3.3,
  brokerCostBasisEur: 9000,
  brokerPnlEur: 300,
  brokerPnlPercent: 3.3,
  positions: 2,
};

export const livePortfolio: LivePortfolio = {
  generatedAt: "2026-09-19T09:00:00.000Z",
  quoteAsOf: "2026-09-19T08:55:00.000Z",
  oldestQuoteAsOf: "2026-09-19T08:55:00.000Z",
  targetSource: "Notion Portfolio · Target Weight 10k + Target Weight",
  targetLines: [{ id: "target-example", name: "Example Corp", target10kWeight: 25, target10kEur: 2500, target25kWeight: 25, target25kEur: 6250 }],
  targetTotals: { target10kWeight: 25, target25kWeight: 25 },
  totals: slice,
  slices: { total: slice, CTO: slice, PEA: { ...slice, marketValueEur: 0, positions: 0 } },
  positions: [{
    id: "position-example",
    targetId: "target-example",
    name: "Example Corp — CTO",
    instrumentType: "Equity",
    account: "CTO",
    sector: "Technology",
    industry: "Software",
    themes: ["AI infrastructure"],
    primaryTheme: "AI infrastructure",
    country: "United States",
    countryExposures: [{ name: "United States", weight: 100 }],
    sectorExposures: [{ name: "Technology", weight: 100 }],
    themeExposures: [{ name: "AI infrastructure", weight: 100 }],
    quantity: 10,
    pruEur: 900,
    brokerPruEur: 900,
    pruSource: "notion-pru",
    costBasisEur: 9000,
    brokerCostBasisEur: 9000,
    marketValueEur: 9300,
    pnlEur: 300,
    pnlPercent: 3.3,
    brokerPnlEur: 300,
    brokerPnlPercent: 3.3,
    weight: 93,
    targetWeight: 25,
    targetEur: 2500,
    target10kWeight: 25,
    target10kEur: 2500,
    quoteSymbol: "EXM",
    nativePrice: 1000,
    nativeCurrency: "USD",
    eurPrice: 930,
    fxRate: 0.93,
    fxMarketTime: "2026-09-19T08:55:00.000Z",
    fetchedAt: "2026-09-19T08:55:00.000Z",
    quoteWarnings: [],
    changePercent: 1.2,
    quoteSource: "reference",
    quoteFreshness: "fresh",
    marketTime: "2026-09-19T08:55:00.000Z",
    companyIds: [company.id],
    notionUrl: "#",
    warning: null,
  }],
  sectors: [{ name: "Technology", valueEur: 9300, weight: 93 }, { name: "Cash", valueEur: 700, weight: 7 }],
  coverage: { live: 1, manual: 0, stale: 0, unavailable: 0, cash: 1, total: 2 },
  reconciliation: { status: "ok", coherent: 2, warnings: 0, errors: 0, issues: [], accountChecks: { CTO: { linesValueEur: 9300, sliceValueEur: 10000, deltaEur: 700 } } },
  calculation: { pnlScope: "unrealized-open-positions", realizedPnlAvailable: false, feesIncluded: false, dividendsIncluded: false, source: "Notion PRU + live quotes + FX" },
};
